const courses = {
  cursos: [
    "Administração",
    "Agrimensura",
    "Agroecologia",
    "Agroindústria",
    "Agronomia",
    "Análise e Desenvolvimento de Sistemas",
    "Antropologia",
    "Aquacultura",
    "Arqueologia",
    "Arquitetura",
    "Arquivística",
    "Artes Cênicas",
    "Artes Visuais",
    "Astronomia",
    "Automação Industrial",
    "Bacharelado em Ciência e Tecnologia",
    "Biblioteconomia",
    "Biocombustíveis",
    "Bioengenharia",
    "Biofísica",
    "Biologia",
    "Biologia Marinha",
    "Biomedicina",
    "Bioquímica",
    "Biotecnologia",
    "Botânica",
    "Cafeicultura",
    "Ciência & Tecnologia",
    "Ciência da Computação",
    "Ciência dos Alimentos",
    "Ciência dos Materiais",
    "Ciência Política",
    "Ciências Aeronáuticas",
    "Ciências Agrárias",
    "Ciências Ambientais",
    "Ciências Atuariais",
    "Ciências Biológicas",
    "Ciências Biomoleculares",
    "Ciências Contábeis",
    "Ciências da Saúde",
    "Ciências do Estado",
    "Ciências do Meio Aquático",
    "Ciências Humanas",
    "Ciências Matemáticas da Terra",
    "Ciências Naturais",
    "Ciências Náuticas",
    "Ciências Sociais",
    "Cinema",
    "Comércio Exterior",
    "Comunicação Social",
    "Construção de Edifícios",
    "Construção de Estradas",
    "Construção Naval",
    "Cooperativismo",
    "Cosmetologia",
    "Dança",
    "Defesa e Gestão Estratégica Internacional",
    "Desenho Industrial",
    "Design de Interiores",
    "Design de Jogos Digitais",
    "Design de Moda",
    "Design de Produto",
    "Design Gráfico",
    "Direito",
    "Drenagem e Irrigação",
    "Ecologia",
    "Economia",
    "Economia Doméstica",
    "Editoração",
    "Educação Artística",
    "Educação do Campo",
    "Educação Física",
    "Energias Renováveis",
    "Enfermagem",
    "Engenharia Aeroespacial",
    "Engenharia Aeronáutica",
    "Engenharia Agrícola",
    "Engenharia Agronômica",
    "Engenharia Ambiental",
    "Engenharia Automotiva",
    "Engenharia Bioquímica",
    "Engenharia Biomédica",
    "Engenharia Cartográfica",
    "Engenharia Civil",
    "Engenharia Civil de Infraestrutura",
    "Engenharia da Informação",
    "Engenharia de Alimentos",
    "Engenharia de Bioprocessos",
    "Engenharia de Computação",
    "Engenharia de Controle e Automação",
    "Engenharia de Energia",
    "Engenharia de Manufatura",
    "Engenharia de Materiais",
    "Engenharia de Minas",
    "Engenharia de Mobilidade",
    "Engenharia de Pesca",
    "Engenharia de Petróleo",
    "Engenharia de Produção",
    "Engenharia de Saúde e Segurança",
    "Engenharia de Sistemas Eletrônicos",
    "Engenharia de Software",
    "Engenharia de Tecidos",
    "Engenharia de Telecomunicações",
    "Engenharia de Transportes e Logística",
    "Engenharia Elétrica",
    "Engenharia Eletrônica",
    "Engenharia Ferroviária e Metroviária",
    "Engenharia Física",
    "Engenharia Florestal",
    "Engenharia Geográfica",
    "Engenharia Geológica",
    "Engenharia Hídrica",
    "Engenharia Industrial Madeireira",
    "Engenharia Matemática",
    "Engenharia Mecânica",
    "Engenharia Mecatrônica",
    "Engenharia Metalúrgica",
    "Engenharia Militar",
    "Engenharia Naval",
    "Engenharia Naval e Oceânica",
    "Engenharia Nuclear",
    "Engenharia Química",
    "Engenharia Sanitária",
    "Engenharia Têxtil",
    "Enologia",
    "Escultura",
    "Esporte e Lazer",
    "Estatística",
    "Eventos",
    "Farmácia",
    "Filosofia",
    "Física",
    "Física Computacional",
    "Física Médica",
    "Fisioterapia",
    "Fonoaudiologia",
    "Fotografia",
    "Fruticultura",
    "Gastronomia",
    "Geofísica",
    "Geografia",
    "Geologia",
    "Geoprocessamento e Sensoriamento Remoto",
    "Gerontologia",
    "Gestão Ambiental",
    "Gestão Comercial",
    "Gestão da Informação",
    "Gestão da Qualidade",
    "Gestão da Tecnologia da Informação",
    "Gestão de Petróleo e Gás",
    "Gestão de Recursos Hídricos",
    "Gestão de Segurança Privada",
    "Gestão do Agronegócio",
    "Gestão em Serviços Jurídicos e Notariais",
    "Gestão Financeira",
    "Gestão Hospitalar",
    "Gestão Portuária",
    "Gestão Pública",
    "Gravurismo",
    "História",
    "História da Arte",
    "Horticultura",
    "Hotelaria",
    "Informática",
    "Informática Biomédica",
    "Jornalismo",
    "Letras",
    "Linguística",
    "Logística",
    "Manutenção Industrial",
    "Marketing",
    "Matemática",
    "Matemática Aplicada",
    "Matemática Computacional",
    "Mecatrônica e Mecânica de Precisão",
    "Medicina",
    "Medicina Veterinária",
    "Meliponicultura",
    "Mercadologia",
    "Meteorologia",
    "Microbiologia e Imunologia",
    "Mineração",
    "Museologia",
    "Música",
    "Nanotecnologia",
    "Naturologia",
    "Negócios Imobiliários",
    "Neurociência",
    "Nutrição",
    "Oceanografia",
    "Odontologia",
    "Oftálmica",
    "Ordenamento do Território",
    "Paisagismo",
    "Pedagogia",
    "Pintura",
    "Processamento de Dados",
    "Processos Escolares",
    "Processos Metalúrgicos",
    "Produção Audiovisual",
    "Produção Cultural",
    "Produção de Aguardente",
    "Produção de Laticínios",
    "Produção de Materiais Plásticos",
    "Produção Fonográfica",
    "Produção Sucroalcooeira",
    "Produção Têxtil",
    "Projetos de Estruturas Aeronáuticas",
    "Psicologia",
    "Publicidade & Propaganda",
    "Química",
    "Química Ambiental",
    "Química Industrial",
    "Quiropraxia",
    "Radiologia",
    "Recursos Humanos",
    "Redes de Computadores",
    "Redes de Telecomunicações",
    "Relações Internacionais",
    "Relações Públicas",
    "Saneamento Ambiental",
    "Saúde Coletiva",
    "Secretariado",
    "Segurança da Informação",
    "Segurança no Trabalho",
    "Segurança Pública",
    "Serviço Social",
    "Silvicultura",
    "Sistemas Biomédicos",
    "Sistemas de Informação",
    "Sistemas de Navegação Fluvial",
    "Sistemas Elétricos",
    "Sistemas Embarcados",
    "Sistemas para Internet",
    "Sociologia",
    "Teatro",
    "Telemática",
    "Teologia",
    "Terapia Ocupacional",
    "Transporte Aéreo",
    "Transporte Terrestre",
    "Turismologia",
    "Urbanismo",
    "Zootecnia",
    "Administração Pública",
    "Acupuntura",
    "Agrocomputação",
    "Agronegócio",
    "Agropecuária",
    "Alimentos",
    "Análise de Dados",
    "Análise de Sistemas",
    "Apicultura e Meliponicultura",
    "Aquicultura",
    "Arquitetura de Dados",
    "Arquitetura e Urbanismo",
    "Arquivologia",
    "Artes",
    "Artes do Espetáculo",
    "Artes e Mídias Digitais",
    "Assessoria Executiva Digital",
    "Atividades de Inteligência e Gestão de Sigilos",
    "Auditoria em Saúde",
    "Automação de Escritórios e Secretariado",
    "Automação e Manufatura Digital",
    "Banco de Dados",
    "Big Data e Inteligência Analítica",
    "Big Data no Agronegócio",
    "Bioenergia",
    "Bioinformática",
    "Blockchain e Criptografia Digital",
    "Canto",
    "Cenografia",
    "Cibersegurança",
    "Ciência de Dados",
    "Ciências da Religião",
    "Ciências Econômicas",
    "Cinema e Audiovisual",
    "Coding",
    "Composição e Regência",
    "Computação",
    "Computação em Nuvem",
    "Comunicação Assistiva",
    "Comunicação Digital",
    "Comunicação e Marketing",
    "Comunicação em Computação Gráfica",
    "Comunicação em Mídias Digitais",
    "Comunicação Intitucional",
    "Conservação e Restauro",
    "Contrução Civil",
    "Construção Ambiental",
    "Controle de Obras",
    "Cosmetologia e Estética",
    "Cozinha Contemporânea",
    "Curso Técnico",
    "Data Science",
    "Defesa Cibernética",
    "Defesa Médica Hospitalar",
    "Desenho de Animação",
    "Desenho e Plástica",
    "Desenvolvimento Back-End",
    "Desenvolvimento de Aplicativos para Dispositivos Móveis",
    "Desenvolvimento de Produtos Pláticos",
    "Desenvolvimento de Sistemas",
    "Desenvolvimento e Gestão de Startups",
    "Desenvolvimento Mobile",
    "Desenvolvimento para Internet",
    "Desenvolvimento para Web",
    "Design",
    "Design de Ambientes",
    "Design de Games",
    "Design Comercial",
    "Design de Animação",
    "Design de Aplicações e Interfaces Digitais",
    "Design de Experiência e de Serviços",
    "Design de Interiores",
    "Design de Moda",
    "Design Digital",
    "Design Editorial",
    "Design Educacional",
    "Devops",
    "Digital Security",
    "Direção",
    "E-Commerce",
    "Educação e Processos de Trabalho: Alimentação Escolar",
    "Educação Especial",
    "Educação Social",
    "Eletrônica Automotiva",
    "Eletrônica Industrial",
    "Eletrotécnica Industrial",
    "Embelezamento e Imagem Pessoal",
    "Empreendedorismo",
    "Energias Renováveis",
    "Engenharia Acústica",
    "Engenharia Agroindustrial",
    "Engenharia Bioenergética",
    "Engenharia Biotecnológica",
    "Engenharia de Agrimensura",
    "Engenharia de Agronegócios",
    "Engenharia de Aquicultura",
    "Engenharia de Automação",
    "Engenharia de Biossistemas",
    "Engenharia de Energia",
    "Engenharia de Gestão",
    "Engenharia de Informação",
    "Engenharia de Instrumentação, Automação e Robótica",
    "Engenharia de Recursos Hídricos",
    "Engenharia de Sistemas",
    "Engenharia Eletrônica",
    "Engenharia de Sistemas Digitais",
    "Engenharia Industrial",
    "Escrita Criativa",
    "Estética e Cosmética",
    "Estilismo",
    "Estradas",
    "Fabricação Mecânica",
    "Filmmaker",
    "Finanças, Blockchain e Criptomoedas",
    "Fitoterapia",
    "Formação de Docentes para a Educação Básica",
    "Futebol",
    "Game Design",
    "Gerenciamento de Redes de Computadores",
    "Gestão Cultural",
    "Gestão de Avaliação",
    "Gestão de Empreendedorismo Digital",
    "Gestão da Produção Industrial",
    "Gestão da Segurança Pública e Patrimonial",
    "Gestão das Organizações do Terceiro Setor",
    "Gestão das Relações Eletrônicas",
    "Gestão de Cidades Inteligentes",
    "Gestão de Cloud Computing",
    "Gestão de Cooperativas",
    "Gestão de Energia e Eficiência Energética",
    "Gestão de Equinocultura",
    "Gestão de Inventário Extrajudicial",
    "Gestão de Investimentos",
    "Gestão de Lojas e Pontos de Vendas",
    "Gestão de Mercado de Capitais",
    "Gestão de Micro e Pequenas Empresas",
    "Gestão de Negócios",
    "Gestão de Pessoas",
    "Gestão de Políticas Públicas",
    "Gestão de Produção Industrial",
    "Gestão de Serviços de Saúde",
    "Gestão de Qualidade na Saúde",
    "Gestão de Recursos Humanos",
    "Gestão de Representação Comercial",
    "Gestão de Resíduos de Serviços de Saúde",
    "Gestão de Saúde Pública",
    "Gestão de Seguros",
    "Gestão Desportiva e de Lazer",
    "Gestão de Telecomunicações",
    "Gestão de Trânsito",
    "Gestão de Turismo",
    "Gestão Empresarial",
    "Gestão em Serviços",
    "Gestão Tributária",
    "Informática para Negócios",
    "Instalações Elétricas",
    "Instrumentação Cirúrgica",
    "Inteligência Artificial",
    "Interiores e Decoração",
    "Internet das Coisas",
    "Investigação e Perícia Criminal",
    "Irrigação e Drenagem",
    "Jogos Digitais",
    "Laticínios",
    "Luteria",
    "Manufatura Avançada",
    "Manutenção de Aeronaves",
    "Massoterapia",
    "Mecânica Automotiva",
    "Mecânica Industrial",
    "Mediação",
    "Microeletrônica",
    "Midias Sociais",
    "Ministério Pastoral",
    "Moda",
    "Multidisciplinar em Dependência Química",
    "Negócios Digitais",
    "Óptica e Optometria",
    "Papel e Celulose",
    "Paramedicina",
    "Petróleo e Gás",
    "Pilotagem Profissional de Aeronaves",
    "Planejamento Logístico de Cargas",
    "Podologia",
    "Polímeros",
    "Política e Gestão Cultural",
    "Políticas Públicas",
    "Processos Ambientais",
    "Processos Gerenciais",
    "Processos Químicos",
    "Processos Agrícola",
    "Produção Agropecuária",
    "Produção Cervejeira",
    "Produção de Cacau e Chocolate",
    "Produção de Cachaça",
    "Produção de Fármacos",
    "Produção de Grãos",
    "Produção de Plástico",
    "Produção Gráfica",
    "Produção Industrial",
    "Produção Leiteira",
    "Produção Multimídia",
    "Produção Musical",
    "Programa Especial de Formação Pedagógica",
    "Projeto de Estruturas Aeronáuticas",
    "Projetos Mecânicos",
    "Propaganda e Marketing",
    "Publicidade",
    "Qualidade de Vida na Contemporaneidade",
    "Rádio, TV e Internet",
    "Refrigeração e Climatização",
    "Rochas Ornamentais",
    "Secretariado Executivo",
    "Segurança Alimentar",
    "Service Design",
    "Sistemas Automotivos",
    "Soldagem",
    "Streaming Profissional",
    "Tecnologia da Informação",
    "Tecnologia Eletrônica",
    "Tecnologia em Controle Ambiental",
    "Tecnologia Mecânica",
    "Tecnologias Digitais",
    "Tecnologias Educacionais",
    "Toxologia Ambiental",
    "Tradutor e Intérprete",
    "Trânsito",
    "Turismo",
    "Tutoria de Educação a Distância",
    "Varejo Digital",
    "Visagismo e Terapias Capilares",
    "Viticultura e Enologia",
    "Nenhum",
    "Outro Curso"
  ],
};
export { courses };
